# Generated by Django 4.2.7 on 2023-11-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServisesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.CharField(max_length=20)),
                ('coursename', models.IntegerField()),
                ('timings', models.CharField(max_length=20)),
                ('startdate', models.DateField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('coursefee', models.IntegerField()),
                ('trainername', models.CharField(max_length=20)),
            ],
        ),
    ]
