# Generated by Django 4.2.7 on 2023-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ratings', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servisesdata',
            name='coursename',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servisesdata',
            name='courseno',
            field=models.IntegerField(),
        ),
    ]
